package request

enum class RequestStatus {
    FRIEND_REQUEST_SELF,
    FRIEND_REQUEST_EXIST,
    FRIEND_REQUEST_NOT_EXIST,
    FRIEND_RELATION_EXIST,
    FRIEND_REQUEST_SUCCESS,
    FRIEND_DELETE_SUCCESS,
    FRIEND_DELETE_FAILED,
}