package style
import androidx.compose.ui.graphics.Color

// purple
val md_theme_light_primarypurple = Color(0xFF6750A4)
val md_theme_light_onPrimarypurple = Color(0xFFFFFFFF)
val md_theme_light_primaryContainerpurple = Color(0xFFEADDFF)
val md_theme_light_onPrimaryContainerpurple = Color(0xFF21005D)
val md_theme_light_secondarypurple = Color(0xFF625B71)
val md_theme_light_onSecondarypurple = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainerpurple = Color(0xFFE8DEF8)
val md_theme_light_onSecondaryContainerpurple = Color(0xFF1D192B)
val md_theme_light_tertiarypurple = Color(0xFF7D5260)
val md_theme_light_onTertiarypurple = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainerpurple = Color(0xFFFFD8E4)
val md_theme_light_onTertiaryContainerpurple = Color(0xFF31111D)
val md_theme_light_errorpurple = Color(0xFFB3261E)
val md_theme_light_onErrorpurple = Color(0xFFFFFFFF)
val md_theme_light_errorContainerpurple = Color(0xFFF9DEDC)
val md_theme_light_onErrorContainerpurple = Color(0xFF410E0B)
val md_theme_light_outlinepurple = Color(0xFF79747E)
val md_theme_light_backgroundpurple = Color(0xFFFEF7FF)
val md_theme_light_onBackgroundpurple = Color(0xFF1D1B20)
val md_theme_light_surfacepurple = Color(0xFFFEF7FF)
val md_theme_light_onSurfacepurple = Color(0xFF1D1B20)
val md_theme_light_surfaceVariantpurple = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariantpurple = Color(0xFF49454F)
val md_theme_light_inverseSurfacepurple = Color(0xFF322F35)
val md_theme_light_inverseOnSurfacepurple = Color(0xFFF5EFF7)
val md_theme_light_inversePrimarypurple = Color(0xFFD0BCFF)
val md_theme_light_surfaceTintpurple = Color(0xFF6750A4)
val md_theme_light_outlineVariantpurple = Color(0xFFCAC4D0)
val md_theme_light_scrimpurple = Color(0xFF000000)

val md_theme_dark_primarypurple = Color(0xFFD0BCFF)
val md_theme_dark_onPrimarypurple = Color(0xFF381E72)
val md_theme_dark_primaryContainerpurple = Color(0xFF4F378B)
val md_theme_dark_onPrimaryContainerpurple = Color(0xFFEADDFF)
val md_theme_dark_secondarypurple = Color(0xFFCCC2DC)
val md_theme_dark_onSecondarypurple = Color(0xFF332D41)
val md_theme_dark_secondaryContainerpurple = Color(0xFF4A4458)
val md_theme_dark_onSecondaryContainerpurple = Color(0xFFE8DEF8)
val md_theme_dark_tertiarypurple = Color(0xFFEFB8C8)
val md_theme_dark_onTertiarypurple = Color(0xFF492532)
val md_theme_dark_tertiaryContainerpurple = Color(0xFF633B48)
val md_theme_dark_onTertiaryContainerpurple = Color(0xFFFFD8E4)
val md_theme_dark_errorpurple = Color(0xFFF2B8B5)
val md_theme_dark_onErrorpurple = Color(0xFF601410)
val md_theme_dark_errorContainerpurple = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainerpurple = Color(0xFFF9DEDC)
val md_theme_dark_outlinepurple = Color(0xFF938F99)
val md_theme_dark_backgroundpurple = Color(0xFF141218)
val md_theme_dark_onBackgroundpurple = Color(0xFFE6E0E9)
val md_theme_dark_surfacepurple = Color(0xFF141218)
val md_theme_dark_onSurfacepurple = Color(0xFFE6E0E9)
val md_theme_dark_surfaceVariantpurple = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariantpurple = Color(0xFFCAC4D0)
val md_theme_dark_inverseSurfacepurple = Color(0xFFE6E0E9)
val md_theme_dark_inverseOnSurfacepurple = Color(0xFF322F35)
val md_theme_dark_inversePrimarypurple = Color(0xFF6750A4)
val md_theme_dark_surfaceTintpurple = Color(0xFFD0BCFF)
val md_theme_dark_outlineVariantpurple = Color(0xFF49454F)
val md_theme_dark_scrimpurple = Color(0xFF000000)


val seedpurple = Color(0xFF50BAA7)

// green

val md_theme_light_primarygreen = Color(0xFF006C46)
val md_theme_light_onPrimarygreen = Color(0xFFFFFFFF)
val md_theme_light_primaryContainergreen = Color(0xFF8FF7BF)
val md_theme_light_onPrimaryContainergreen = Color(0xFF002112)
val md_theme_light_secondarygreen = Color(0xFF4E6356)
val md_theme_light_onSecondarygreen = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainergreen = Color(0xFFD0E8D7)
val md_theme_light_onSecondaryContainergreen = Color(0xFF0B1F15)
val md_theme_light_tertiarygreen = Color(0xFF3C6472)
val md_theme_light_onTertiarygreen = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainergreen = Color(0xFFC0E9F9)
val md_theme_light_onTertiaryContainergreen = Color(0xFF001F28)
val md_theme_light_errorgreen = Color(0xFFBA1A1A)
val md_theme_light_errorContainergreen = Color(0xFFFFDAD6)
val md_theme_light_onErrorgreen = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainergreen = Color(0xFF410002)
val md_theme_light_backgroundgreen = Color(0xFFFBFDF8)
val md_theme_light_onBackgroundgreen = Color(0xFF191C1A)
val md_theme_light_outlinegreen = Color(0xFF707972)
val md_theme_light_inverseOnSurfacegreen = Color(0xFFEFF1ED)
val md_theme_light_inverseSurfacegreen = Color(0xFF2E312E)
val md_theme_light_inversePrimarygreen = Color(0xFF73DAA5)
val md_theme_light_surfaceTintgreen = Color(0xFF006C46)
val md_theme_light_outlineVariantgreen = Color(0xFFC0C9C1)
val md_theme_light_scrimgreen = Color(0xFF000000)
val md_theme_light_surfacegreen = Color(0xFFF8FAF5)
val md_theme_light_onSurfacegreen = Color(0xFF191C1A)
val md_theme_light_surfaceVariantgreen = Color(0xFFDCE5DC)
val md_theme_light_onSurfaceVariantgreen = Color(0xFF404943)

val md_theme_dark_primarygreen = Color(0xFF73DAA5)
val md_theme_dark_onPrimarygreen = Color(0xFF003822)
val md_theme_dark_primaryContainergreen = Color(0xFF005233)
val md_theme_dark_onPrimaryContainergreen = Color(0xFF8FF7BF)
val md_theme_dark_secondarygreen = Color(0xFFB4CCBB)
val md_theme_dark_onSecondarygreen = Color(0xFF203529)
val md_theme_dark_secondaryContainergreen = Color(0xFF364B3F)
val md_theme_dark_onSecondaryContainergreen = Color(0xFFD0E8D7)
val md_theme_dark_tertiarygreen = Color(0xFFA4CDDD)
val md_theme_dark_onTertiarygreen = Color(0xFF053542)
val md_theme_dark_tertiaryContainergreen = Color(0xFF234C59)
val md_theme_dark_onTertiaryContainergreen = Color(0xFFC0E9F9)
val md_theme_dark_errorgreen = Color(0xFFFFB4AB)
val md_theme_dark_errorContainergreen = Color(0xFF93000A)
val md_theme_dark_onErrorgreen = Color(0xFF690005)
val md_theme_dark_onErrorContainergreen = Color(0xFFFFDAD6)
val md_theme_dark_backgroundgreen = Color(0xFF191C1A)
val md_theme_dark_onBackgroundgreen = Color(0xFFE1E3DF)
val md_theme_dark_outlinegreen = Color(0xFF8A938B)
val md_theme_dark_inverseOnSurfacegreen = Color(0xFF191C1A)
val md_theme_dark_inverseSurfacegreen = Color(0xFFE1E3DF)
val md_theme_dark_inversePrimarygreen = Color(0xFF006C46)
val md_theme_dark_surfaceTintgreen = Color(0xFF73DAA5)
val md_theme_dark_outlineVariantgreen = Color(0xFF404943)
val md_theme_dark_scrimgreen = Color(0xFF000000)
val md_theme_dark_surfacegreen = Color(0xFF111412)
val md_theme_dark_onSurfacegreen = Color(0xFFC5C7C3)
val md_theme_dark_surfaceVariantgreen = Color(0xFF404943)
val md_theme_dark_onSurfaceVariantgreen = Color(0xFFC0C9C1)


val seedgreen = Color(0xFF005435)




